
export const USERS_GET_REQUEST = 'USERS_GET_REQUEST';
export const USERS_GET_RESPONSE_SUCCESS = 'USERS_GET_RESPONSE_SUCCESS';

export const USERS_LOAD_MORE_REQUEST = 'USERS_LOAD_MORE_REQUEST';
export const USERS_LOAD_MORE_RESPONSE_SUCCESS = 'USERS_LOAD_MORE_RESPONSE_SUCCESS';